// @ts-nocheck
"use client";
import { useState, useEffect } from "react";
import {
  ClipboardList,
  Factory,
  FileText,
  Leaf,
  CheckCircle,
  Recycle,
  Globe,
  Lightbulb,
  Users,
  DollarSign,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Poppins } from "next/font/google";
import Link from "next/link";
import { getEprStats } from "@/utils/db/actions";

const poppins = Poppins({
  weight: ["300", "400", "600"],
  subsets: ["latin"],
  display: "swap",
});

export default function EPRPage() {
  const [impactData, setImpactData] = useState({
    companiesRegistered: 0,
    wasteCollected: 0,
    complianceReports: 0,
  });

  useEffect(() => {
    async function fetchEprStats() {
      try {
        const stats = await getEprStats();
        setImpactData(stats);
      } catch (error) {
        console.error("Error fetching EPR stats:", error);
      }
    }
    fetchEprStats();
  }, []);

  return (
    <div className={`container mx-auto px-4 py-16 ${poppins.className}`}>
      {/* Hero Section */}
      <section
        className="relative w-full h-screen flex items-center justify-center text-center bg-cover bg-no-repeat bg-top"
        style={{
          backgroundImage: "url('/EPR-Infographic-2048x1996.webp')", // Change to your actual image path
        }}
      >
        {/* Dark Overlay */}
        <div className="absolute inset-0 bg-white bg-opacity-30"></div>

        {/* Text Content */}
        <div className="relative z-10 text-gray-800 px-4">
          <h1 className="text-6xl font-bold mb-6 tracking-tight">
            Extended Producer{" "}
            <span className="text-green-600">Responsibility (EPR)</span>
          </h1>
          <p className="text-xl max-w-3xl mx-auto leading-relaxed mb-8">
            Extended Producer Responsibility (EPR) is a regulatory framework
            ensuring that producers take full responsibility for the waste
            generated by their products. This policy drives sustainable waste
            management and promotes a circular economy.
          </p>
          <Link href="/EPR/register">
            <Button className="bg-green-600 hover:bg-green-700 text-white text-lg py-6 px-10 rounded-full font-medium transition-all duration-300 ease-in-out transform hover:scale-105">
              Register for EPR
              <CheckCircle className="ml-2 h-5 w-5" />
            </Button>
          </Link>
        </div>
      </section>
      <br />

      {/* <br />

      <div className="flex justify-center">
        <img
          src="EPR-Infographic-2048x1996.webp" // Change the path accordingly
          alt="EPR Rules Illustration"
          className="w-full max-w-md rounded-xl shadow-lg"
        />
      </div>
      <br /> */}

      {/* Features Section */}
      <section className="grid md:grid-cols-3 gap-10 mb-20">
        <FeatureCard
          icon={Factory}
          title="Producer Responsibility"
          description="Manufacturers must ensure proper waste management, recycling, and compliance with sustainability regulations."
        />
        <FeatureCard
          icon={FileText}
          title="EPR Compliance Reports"
          description="Companies must submit detailed reports on waste collection, recycling efforts, and regulatory compliance."
        />
        <FeatureCard
          icon={ClipboardList}
          title="Government Regulations"
          description="Follow updated policies and laws to ensure proper disposal and recycling of e-waste."
        />
      </section>

      {/* Impact Section */}
      <section className="bg-white p-10 rounded-3xl shadow-lg mb-20">
        <h2 className="text-4xl font-bold mb-12 text-center text-gray-800">
          EPR Impact
        </h2>
        <div className="grid md:grid-cols-3 gap-6">
          <ImpactCard
            title="Registered Companies"
            value={impactData.companiesRegistered}
            icon={Factory}
          />
          <ImpactCard
            title="Waste Collected"
            value={`${impactData.wasteCollected} kg`}
            icon={Leaf}
          />
          <ImpactCard
            title="Compliance Reports Submitted"
            value={impactData.complianceReports}
            icon={FileText}
          />
        </div>
      </section>

      {/* Why EPR Matters Section */}
      <section className="text-center mb-20">
        <h2 className="text-5xl font-extrabold mb-6 text-gray-800">
          Why <span className="text-green-600">EPR Matters?</span>
        </h2>
        <p className="text-xl text-gray-600 max-w-4xl mx-auto leading-relaxed mb-12">
          Extended Producer Responsibility (EPR) is more than just a policy—it’s
          a movement toward sustainability, circular economy, and environmental
          stewardship. By enforcing EPR, we can transform waste into valuable
          resources, ensuring a cleaner and greener future.
        </p>

        <div className="grid md:grid-cols-2 gap-10 max-w-5xl mx-auto">
          <FeatureBox
            icon={Recycle}
            title="Boosting Recycling & Resource Recovery"
            description="EPR promotes efficient recycling processes, reducing the dependency on raw materials and conserving natural resources."
          />
          <FeatureBox
            icon={Globe}
            title="Minimizing Environmental Impact"
            description="Prevents hazardous waste from polluting landfills and water bodies, reducing long-term damage to ecosystems."
          />
          <FeatureBox
            icon={FileText}
            title="Regulatory Compliance & Accountability"
            description="Ensures producers adhere to waste management laws, making them accountable for their products’ lifecycle."
          />
          <FeatureBox
            icon={Lightbulb}
            title="Encouraging Eco-Friendly Innovation"
            description="Motivates companies to design sustainable products with recyclable materials, reducing e-waste generation."
          />
          <FeatureBox
            icon={Users}
            title="Creating Green Jobs"
            description="Supports employment in the waste management and recycling sector, driving economic growth while preserving the environment."
          />
          <FeatureBox
            icon={DollarSign}
            title="Economic & Social Benefits"
            description="By investing in EPR, companies gain consumer trust, reduce costs through material reuse, and contribute to sustainable development."
          />
        </div>
      </section>

      <section className="bg-gray-100 p-12 rounded-3xl shadow-lg mb-20">
        <h2 className="text-4xl font-bold mb-8 text-center text-gray-800">
          Key <span className="text-green-600">EPR Rules</span>
        </h2>
        <p className="text-lg text-gray-600 max-w-3xl mx-auto text-center mb-10">
          Understanding EPR regulations is essential for compliance and
          sustainability. Here are some key guidelines that producers must
          follow.
        </p>

        <div className="grid md:grid-cols-3 gap-8">
          <RuleCard
            icon={ClipboardList}
            title="Mandatory Registration"
            description="All producers, importers, and brand owners must register under the EPR framework to ensure accountability."
          />

          <RuleCard
            icon={CheckCircle}
            title="Waste Collection Targets"
            description="Companies must meet annual waste collection targets based on their product sales and type."
          />

          <RuleCard
            icon={Factory}
            title="Recycling & Disposal"
            description="E-waste must be recycled through authorized recyclers, ensuring safe disposal of hazardous components."
          />

          <RuleCard
            icon={FileText}
            title="Annual Compliance Reports"
            description="Producers must submit detailed reports on waste management efforts, ensuring transparency in the system."
          />

          <RuleCard
            icon={Leaf}
            title="Eco-Friendly Packaging"
            description="Companies should prioritize biodegradable and recyclable packaging materials to minimize waste."
          />

          <RuleCard
            icon={ClipboardList}
            title="Penalty for Non-Compliance"
            description="Strict penalties are imposed on companies failing to meet their EPR obligations."
          />
        </div>
      </section>
    </div>
  );
}

// Impact Card Component
function ImpactCard({ title, value, icon: Icon }) {
  return (
    <div className="p-6 rounded-xl bg-gray-50 border border-gray-100 transition-all duration-300 ease-in-out hover:shadow-md">
      <Icon className="h-10 w-10 text-green-500 mb-4" />
      <p className="text-3xl font-bold mb-2 text-gray-800">{value}</p>
      <p className="text-sm text-gray-600">{title}</p>
    </div>
  );
}

// Feature Card Component
function FeatureCard({ icon: Icon, title, description }) {
  return (
    <div className="bg-white p-8 rounded-xl shadow-md hover:shadow-lg transition-all duration-300 ease-in-out flex flex-col items-center text-center">
      <div className="bg-green-100 p-4 rounded-full mb-6">
        <Icon className="h-8 w-8 text-green-600" />
      </div>
      <h3 className="text-xl font-semibold mb-4 text-gray-800">{title}</h3>
      <p className="text-gray-600 leading-relaxed">{description}</p>
    </div>
  );
}

// EPR Rules
function RuleCard({ icon: Icon, title, description }) {
  return (
    <div className="p-8 bg-white rounded-xl shadow-md hover:shadow-lg transition-all duration-300 ease-in-out flex flex-col items-center text-center">
      <div className="bg-green-100 p-4 rounded-full mb-4">
        <Icon className="h-10 w-10 text-green-600" />
      </div>
      <h3 className="text-xl font-semibold mb-3 text-gray-800">{title}</h3>
      <p className="text-gray-600 leading-relaxed">{description}</p>
    </div>
  );
}

// Why EPR Matters Feature Box
function FeatureBox({ icon: Icon, title, description }) {
  return (
    <div className="bg-white p-6 rounded-xl shadow-lg flex items-start space-x-4 hover:shadow-xl transition-all duration-300 ease-in-out">
      <Icon className="h-10 w-10 text-green-500" />
      <div>
        <h3 className="text-xl font-semibold text-gray-800 mb-2">{title}</h3>
        <p className="text-gray-600">{description}</p>
      </div>
    </div>
  );
}
